Class_Based_Views/CBVpro/CBVapp/urls.py
from django.urls import path,re_path
from CBVapp import views

app_name="CBVapp"


urlpatterns = [
    path('',views.SchoolListView.as_view(),name="list"),
    path("create/",views.SchoolCreateView.as_view(),name="create"),
    re_path(r'^(?P<pk>[-\w]+)/$',views.SchoolDetailView.as_view(),name="detail"),
    re_path(r'^update/(?P<pk>[-\w]+)/$',views.SchoolUpdateView.as_view(),name="update"),
    re_path(r'^delete/(?P<pk>[-\w]+)/$',views.SchoolDeleteView.as_view(),name="delete"),

]

Class_Based_Views/CBVpro/CBVpro/urls.py
from django.contrib import admin
from django.urls import path,include
from CBVapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.About.as_view()),
    path("CBVapp/",include("CBVapp.urls", namespace="CBVapp")),
]

Class_Based_Views/CBVpro/CBVapp/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    name=models.CharField(max_length=200)
    location=models.CharField(max_length=200)
    principal=models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("CBVapp:detail",kwargs={"pk":self.pk})
    


class Student(models.Model):
    name=models.CharField(max_length=200)
    age=models.PositiveIntegerField()
    school=models.ForeignKey(School,on_delete=models.CASCADE,related_name="students")

    def __str__(self):
        return self.name

Class_Based_Views/CBVpro/CBVapp/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,DeleteView,UpdateView
from  django.urls import reverse_lazy
from . import models

# Create your views here.


# Creating a Class Based views
class About(TemplateView):
    template_name="index.html"



class SchoolListView(ListView):
    context_object_name="schools"
    model=models.School


class SchoolDetailView(DetailView):
    context_object_name="school_details"
    model=models.School
    template_name="CBVapp/student_details.html"


class SchoolCreateView(CreateView):
    fields=("name","principal","location")
    model=models.School


class SchoolUpdateView(UpdateView):
    fields=("name","principal")
    model=models.School


class SchoolDeleteView(DeleteView):
    model=models.School
    success_url=reverse_lazy("CBVapp:list")

Class_Based_Views/CBVpro/CBVapp/templates/CBVapp/school_confirm_delete.html
{% extends "CBVapp/stu_base.html" %}
{% block body_block %}

<h1>Delete {{school.name}}?</h1>
<form  method="POST">
{% csrf_token %}

<input type="submit" class="btn btn-danger" name="" value="Delete">
<a class="btn btn-dark" href="{% url 'CBVapp:detail' pk=school.pk  %}">Cancel</a>
</form>


{% endblock %}

Class_Based_Views/CBVpro/CBVapp/templates/CBVapp/school_form.html
{% extends "CBVapp/stu_base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
    create school
  {% else %}
    update school
  {% endif %}
</h1>
<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>

  <input type="submit" class="btn btn-primary" name="" value="Submit">

</form>

{% endblock %}

Class_Based_Views/CBVpro/CBVapp/templates/CBVapp/school_list.html
{%  extends "CBVapp/stu_base.html" %}
{% block body_block %}

<h1>Welcome to the list of all the schools!!</h1>
<ol>
  {% for school in schools %}
  <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
  {% endfor %}
</ol>

{% endblock %}

Class_Based_Views/CBVpro/CBVapp/templates/CBVapp/stu_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base html file</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'CBVapp:list' %}">Schools</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link " href="{% url "admin:index" %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <div class="container">
       {% block body_block %}
       {% endblock %}
    </div>


  </body>
</html>

Class_Based_Views/CBVpro/CBVapp/templates/CBVapp/student_details.html
{% extends 'CBVapp/stu_base.html' %}
{% block body_block %}

<div class="border-0">
  <div class="bg-success p-2 text-dark bg-opacity-25">
     <h1 class="p-3">Welcome to the School Details Page:</h1>
     <h2>School Details:</h2>
     <p>Name: {{school_details.name}}</p>
     <p>Principal: {{school_details.principal}}</p>
     <p>Location: {{school_details.location}}</p>
     <h3>Students: </h3>
     {% for student in school_details.students.all %}
       <p>{{student.name}} who is {{student.age}} years old.</p>
     {% endfor %}
  </div>
</div>
<div class="container p-3">
  <p><a class="btn btn-primary" href="{% url 'CBVapp:update' pk=school_details.pk %}">Update</a></p>
</div>

{% endblock %}

Class_Based_Views/CBVpro/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>base html file</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container">
       {% block body_block %}
       {% endblock %}
    </div>


  </body>
</html>

Class_Based_Views/CBVpro/templates/index.html
{% extends "base.html" %}
{% block body_block %}

<div class="border-0">
  <div class="bg-success p-2 text-dark bg-opacity-25">
     <h1 class="p-3">Home Page</h1>
  </div>

</div>


{% endblock %}