Django_level_four/UserPro/UserApp/urls.py
from django.urls import path
from UserApp import views

#template tagging
app_name="UserApp"

urlpatterns = [

  path("register/",views.register,name="registration"),
  path("user_login/",views.user_login,name="user_login"),

]

Django_level_four/UserPro/UserPro/urls.py
from django.contrib import admin
from django.urls import path,include
from UserApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.index,name="index"),
    path("UserApp/",include("UserApp.urls")),
    path("logout/",views.user_logout,name="logout"),
    path("special/",views.special,name="special"),

]

Django_level_four/UserPro/UserApp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    # create relationship
    user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True,)

    # Portfolio site
    portfolio=models.URLField(blank=True)

    # profile pic
    profile_pic=models.ImageField(upload_to="profile_pics",blank=True)

    def __str__(self):
        return self.user.username

Django_level_four/UserPro/UserApp/forms.py
from django import forms
from django.contrib.auth.models import User
from UserApp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ("username","email", "password")



class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfileInfo
        fields = ("portfolio","profile_pic")

Django_level_four/UserPro/UserApp/views.py
from django.shortcuts import render
from UserApp.forms import UserProfileForm,UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def index(request):
    return render(request,"UserApp/index.html")


def register(request):
    # If you are not registered yet
    registered=False

   # If you have filled the form
    if request.method == "POST":
       #Get the user form info
        user_form=UserForm(data=request.POST)
        # get the profile form info
        profile_form=UserProfileForm(data=request.POST)


      # If the filled information is valid
        if user_form.is_valid() and profile_form.is_valid():
            # Save the info once it is valid
            user=user_form.save()
            # Set the password for the user
            user.set_password(user.password)
            user.save()
            login(request, user)

            profile=profile_form.save(commit=False)
            profile.user=user

            if "profile_pic" in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered=True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form=UserForm()
        profile_form=UserProfileForm()

    return render(request,"UserApp/registration.html",{
                                                       'user_form':user_form,
                                                       'profile_form':profile_form,
                                                       'registered':registered,
                                                        })




def user_login(request):
    if request.method == "POST":
        password=request.POST.get('password')
        username=request.POST.get('username')

        user=authenticate(request,username=username,password=password)

        if user :
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not Active")
        else:

            print("Someone tried to login into your account and failed!")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid Login Details Entered")
    else:
        return render(request,"UserApp/login.html",{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(request):
    return HttpResponse("You're logged in, Nice!")

Django_level_four/UserPro/templates/UserApp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
      <a class="navbar-brand" href="#">UserApp</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

       <ul class="navbar-nav">
         <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
         <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
         <li class="nav-item"><a class="nav-link" href="{% url 'UserApp:registration'%}">Registration</a></li>
         {% if user.is_authenticated %}
           <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log Out</a></li>
         {% else %}
           <li  class="nav-item"> <a class="nav-link" href="{% url 'UserApp:user_login' %}">Log In</a></li>
         {% endif %}
       </ul>
       </div>
      </div>

    </nav>

    {% block body_block %}
    {% endblock %}

  </body>
</html>

Django_level_four/UserPro/templates/UserApp/index.html
<!DOCTYPE html>
{% extends "UserApp/base.html" %}
  {% block body_block %}
      <div class="container">
       <div class="p-3 mb-2 bg-primary text-white border-0">
        <h1>Django App. This blog shows how to authenticate the users</h1>

       </div>
     </div>
  {% endblock %}

Django_level_four/UserPro/templates/UserApp/login.html
<!--Login Page-->
<!DOCTYPE html>
{% extends "UserApp/base.html" %}
{% block body_block %}
  <div class="container">
    <div class="p-3 mb-2 bg-primary text-white border-0">
      <h1>Please Log In</h1>

       <form action="{% url 'UserApp:user_login' %}" method="POST">
           {% csrf_token %}
           <div class="mb-2 row pt-3">
             <label for="user_name" class="col-sm-2  form-label">User Name:</label>
             <div class="col-sm-10">

             <input type="text" id ="user_name" class="form-control" name="username" placeholder="Enter username">
             </div>
           </div>
           <div class="mb-2 row ">
             <label for="password" class="col-sm-2 form-label">Password:</label>
             <div class="col-sm-10">
             <input id="password"  type="password" class="form-control" name="password" value="">
           </div>
           </div>
           <div class="mb-3">
             <input type="submit"  class="btn btn-outline-light mb-3" name="" value="Log In">
           </div>
       </form>

    </div>

  </div>
{%endblock%}

Django_level_four/UserPro/templates/UserApp/registration.html
<!DOCTYPE html>
{% extends "UserApp/base.html" %}
 {% load static %}
  {% block body_block %}
  <div class="container">
   <div class="p-3 mb-2 bg-primary text-white border-0">
    {% if registered %}
    <h1>Thank You for registering</h1>
    {% else %}
    <h2>Register Here!</h2>
    <h3>Fill out the form:</h3>
    <form class="p-3 mb-2" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
       <table>{{user_form.as_table}}
              {{profile_form.as_table}}
       </table>
       <input type="submit" class="btn btn-outline-light" name="" value="Register">
    {% endif %}
    </form>
   </div>
  </div>
  {% endblock %}